name: "1.Compress files"

on:
  workflow_dispatch:
  
jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Compress files "
      env:
        EMAIL: ${{ secrets.GH_EMAIL }}
        NAME: ${{ secrets.GH_USERNAME }}
        TOKEN: ${{ secrets.TOKEN }}

      steps:
      - name: Compress files
        run: |
          git config --global user.email "${{ env.EMAIL }}"
          git config --global user.name "${{ env.NAME }}"
          git clone https:///${{ env.TOKEN }}@github.com/${{github.repository}}.git
          cd $(echo ${{github.repository}} | awk -F'/' '{print $2}')
          tar czvf file.tar.gz web.js entrypoint.sh package.json server.js
          git add .
          git commit -m "Upload Via Github Actions, $(date "+%Y/%m/%d")"
          git push